### ISSUE TITLE
new release/Tag with current Laravel 6 support

### ISSUE THREAD

**Issue by nlappe** [alariva/laravel-email-domain-blacklist#9]
Hey, i just found your package and was a bit confused i couldnt composer require it in my project.
Turns out, Laravel 6 support is in the master branch but not in any release, therefore you'd have to composer require the dev-master which is kinda ... meh.

It would be cool if you could create a release 1.0.2 that includes the Laravel 6 support.

Thanks for creating this package - it sure saves me some annoying boilerplate :)

**Comment by alariva** [comment]
Hi @nlappe , thanks for the suggestion. I'll keep you posted on this.

**Comment by alariva** [comment]
[https://github.com/alariva/laravel-email-domain-blacklist/releases/tag/v1.0.2](v1.0.2) should do the trick, let me know any other issues may appear. Thanks!

**Comment by nlappe** [comment]
Just tried it out and it worked fine.

Also i gave the blacklist validator a try and it worked flawless, you really saved me some annoying hours - thanks :)
